version: "3"
   
services:
  mysql:
    platform: linux/x86_64 
    restart: always
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      # - MYSQL_DATABASE=sjahn
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3306:3306"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volumes/data/mysql:/var/lib/mysql/
    networks:
      - net

  redis:
    restart: always
    image: 'redis'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - './volumes/data/redis:/data'
    networks:
      - net

networks:
  net:
    driver: bridge