version: "3"
   
services:
  mariadb:
    restart: always
    image: mariadb:10.1
    container_name: mariadb
    environment:
      - TZ="Asia/Seoul"
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/data/mariadb:/var/lib/mysql/
      - ./config/my.cnf:/etc/mysql/my.cnf

  redis:
    restart: always
    image: 'redis'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - './volumes/data/redis:/data'
